fixed tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,5 +25,8 @@ jobs:
           -I "/opt/soapui/projects/Soap-try-soapui-project.xml" > tests/testOutput.txt
 
       - name: verify there are no test failures
-        run: if grep -q "(0 failed)" tests/testOutput.txt;
-        then echo "Error: Found the line in the output" exit 1 fi
+        run: | 
+          if grep -q "(0 failed)" tests/testOutput.txt
+          then echo "Error: Found the line in the output" 
+          exit 1 
+          fi
